name: "Generate Producerflow API client libraries"
on:
  push:
    branches: [main]
    paths: [buf.yaml, buf.gen.yaml, producerflow/**]
  workflow_dispatch:
concurrency:
  group: buf-generate
  cancel-in-progress: true
permissions:
  contents: write
  pull-requests: write

env:
  NODE_VERSION: 22
  GO_VERSION: 1.24.0
  PROTO_GEN_ES_VERSION: 2.5.2
  PROTO_GEN_CONNECT_ES_VERSION: 1.6.1

jobs:
  buf-generate:
    name: "Generate Producerflow API client libraries"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Download Go dependencies
        run: go mod download
      - name: 'Install protoc-gen-doc'
        run: go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest
      - name: 'Install @bufbuild/protoc-gen-es'
        run: npm i -g @bufbuild/protoc-gen-es@${{ env.PROTO_GEN_ES_VERSION }}
      - name: 'Install @connectrpc/protoc-gen-connect-es'
        run: npm i -g @connectrpc/protoc-gen-connect-es@${{ env.PROTO_GEN_CONNECT_ES_VERSION }}
      - name: Check buf version
        run: buf --version
      - name: Run buf generate
        run: buf generate
      - name: Close existing PRs and delete branches
        run: |
          echo "Searching for existing PRs with pattern: dev/producerflowapi/regenerate-api-clients-*"
          
          # List all open PRs to debug
          echo "All open PRs:"
          gh pr list --state open --json number,title,headRefName || echo "Failed to list PRs"
          
          # Find existing PRs with our specific pattern
          echo "Searching for PRs with regenerate-api-clients pattern..."
          existing_prs=$(gh pr list --state open --json number,headRefName | jq -r '.[] | select(.headRefName | startswith("dev/producerflowapi/regenerate-api-clients-")) | .number' 2>/dev/null || echo "")
          
          echo "Found PR numbers: '$existing_prs'"
          
          if [ ! -z "$existing_prs" ] && [ "$existing_prs" != "" ]; then
            echo "Found existing PRs to close: $existing_prs"
            echo "$existing_prs" | while read -r pr_number; do
              if [ ! -z "$pr_number" ]; then
                echo "Processing PR #$pr_number"
                
                # Get the branch name first
                branch_name=$(gh pr view $pr_number --json headRefName --jq -r '.headRefName' 2>/dev/null || echo "")
                echo "Branch name: $branch_name"
                
                # Close the PR
                echo "Closing PR #$pr_number"
                gh pr close $pr_number --comment "Closing this PR as a new API client regeneration is being created." || echo "Failed to close PR #$pr_number"
                
                # Delete the branch if we got the name
                if [ ! -z "$branch_name" ] && [ "$branch_name" != "null" ]; then
                  echo "Deleting branch: $branch_name"
                  git push origin --delete "$branch_name" 2>/dev/null || echo "Branch $branch_name may not exist or already deleted"
                fi
              fi
            done
          else
            echo "No existing PRs found to close"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore(producerflowapi): regenerate client libraries"
          title: "chore(producerflowapi): regenerate client libraries"
          body: |
            This PR contains automatically generated changes to the Producerflow API client libraries.
            
            Generated from the latest protocol buffer definitions in the `producerflow/` directory.
            
            ## Changes
            - Updated Go client libraries
            - Updated TypeScript client libraries
            
            ## Review
            Please review the generated code to ensure all changes are as expected.
          branch: "dev/producerflowapi/regenerate-api-clients-${{ github.run_number }}"
          delete-branch: true

