name: Go Build Test

on:
  push:
    branches: [ main ]
    paths:
      - 'gen/go/**'
  pull_request:
    paths:
      - 'gen/go/**'
  workflow_dispatch:

jobs:
  go-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.0'
        cache: true

    - name: Download Go dependencies
      run: go mod download

    - name: Verify Go generated code compiles
      run: |
        echo "Testing Go code compilation..."
        if [ -d "gen/go" ]; then
          go build ./...
          echo "✅ Go generated code compiles successfully"
        else
          echo "❌ No generated Go code found in gen/go"
          exit 1
        fi

    - name: Run Go tests (if any exist)
      run: |
        if find . -name "*_test.go" -type f | grep -q .; then
          echo "Running Go tests..."
          go test ./... -v
        else
          echo "No Go tests found, skipping..."
        fi 