name: TypeScript Build Test

on:
  push: 
    branches: [ main ]
    paths:
      - 'gen/ts/**'
      - 'package-lock.json'
      - 'package.json'
  pull_request:
    branches: [main]
    paths:
      - 'gen/ts/**'
      - 'package-lock.json'
      - 'package.json'
  workflow_dispatch:

env:
  NODE_VERSION: 22

jobs:
  ts-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          gen/ts/node_modules
        key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('gen/ts/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ env.NODE_VERSION }}-
    - name: Check TypeScript compilation
      run: |
        if [ -d "gen/ts" ] && [ "$(find gen/ts -name "*.ts" | wc -l)" -gt 0 ]; then
          echo "Setting up TypeScript compilation test..."
          cd gen/ts
          echo "Type-checking TypeScript files..."
          npm install
          npm run typecheck
          echo "✅ TypeScript type-checks successfully"
        else
          echo "❌ No generated TypeScript files found in gen/ts"
          exit 1
        fi 